# Callbacks

<!-- ðŸ¤”ðŸ¤”ðŸ¤”ðŸ¤”ðŸ¤” QUIZ 1 ðŸ¤”ðŸ¤”ðŸ¤”ðŸ¤”ðŸ¤” -->

## Handling errors, error first callbacks

* Read the below code and then do quizz 2 and 3

```js
const fs = require("fs");

fs.readFile("./files/demofile.txt", { encoding: "utf8" }, (err, data) => {
  if (err) {
    // next(err) <- can pass up the chain

    // console.error(err); <- can log and continue
    // return
    throw err; // <- can error and exit
  } else {
    console.log(data);
  }
});
```

<!-- ðŸ¤”ðŸ¤”ðŸ¤”ðŸ¤”ðŸ¤” QUIZ 2 + 3 ðŸ¤”ðŸ¤”ðŸ¤”ðŸ¤”ðŸ¤” -->

## Callback Hell

```js
function doAsyncTask(cb) {
  setImmediate(() => {
    console.log("Async Task Calling Callback");
    cb();
  });
}

doAsyncTask(() => {
  doAsyncTask(() => {
    doAsyncTask(() => {
      doAsyncTask(() => {
        doAsyncTask(() => {
          doAsyncTask(() => {
            doAsyncTask(() => {
              doAsyncTask(() => {
                doAsyncTask(() => {
                  doAsyncTask(() => {});
                });
              });
            });
          });
        });
      });
    });
  });
});
```
